name: senn
channels:
  - Lyken
  - anaconda
  - ak_93
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.8
  - matplotlib
  - pytorch
  - cpuonly
  - torchvision
  - tensorboard
  - scipy
  - pandas
  - scikit-learn
  - jupyter

